// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "test": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=goa-api-test/design
// --out=$(GOPATH)/src/goa-api-test
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// TestHref returns the resource href.
func TestHref(testID interface{}) string {
	paramtestID := strings.TrimLeftFunc(fmt.Sprintf("%v", testID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/tests/%v", paramtestID)
}
