package design

import (
	. "github.com/goadesign/goa/design" // Use . imports to enable the DSL
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("test", func() {
	Title("GOA Test API")
	Description("Goa test")
	Contact(func() {
		Name("GOA TEst")
		Email("goa@test.com")
		URL("https://goa.test.com")
	})
	Docs(func() {
		Description("readme")
		URL("https://goa.test.com")
	})
	Scheme("http")
	Host("localhost:8080")
	Consumes("application/json") // Media types supported by the API
	Produces("application/json") // Media types generated by the API
})
