// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "test": swagger TestHelpers
//
// Command:
// $ goagen
// --design=goa-api-test/design
// --out=$(GOPATH)/src/goa-api-test
// --version=v1.3.1

package test
